export default [
  /*carhHood:*/ {
    name: "CARHARTT WIP HOODIE", //CARHARTT WIP HOODED KLICKS SWEATSHIRT
    category: "hoodie",
    tagName: "carhHood",
    price: 113.0,
    numbers: 0,
    inCart: false, //"./images/carhHood.jpg",
    image: "https://static.footshop.com/236728/47495.jpg", //"./images/carhHood.jpg",
  },
  /*stHood:*/ {
    name: "STÜSSY BASIC HOODIE",
    category: "hoodie",
    tagName: "stHood",
    price: 114.0,
    numbers: 0,
    inCart: false, //"./images/stHood.jpg",
    image: "https://static.footshop.com/256274/51950.jpg", //"./images/stHood.jpg",
  },
  /*vnHood:*/ {
    name: "VANS X GOLDBERG HOODIE", //VANS X JIM GOLDBERG SWEATSHIRT
    category: "hoodie",
    tagName: "vnHood",
    price: 100.0,
    numbers: 0,
    inCart: false, //"./images/vnHood.jpg",
    image: "https://static.footshop.com/254686/51173.jpg", //"./images/vnHood.jpg",
  },
  /*carhTshirt:*/ {
    name: "CARHARTT WIP POCKET TEE",
    category: "tee",
    tagName: "carhTshirt",
    price: 33.0,
    numbers: 0,
    inCart: false, //"./images/carhTshirt.jpg",
    image: "https://static.footshop.com/254090/51571.jpg", //"./images/carhTshirt.jpg",
  },
  /*stTshirt:*/ {
    name: "STÜSSY LONG SLEEVE TEE", //STÜSSY BLEACH STRIPE CREW LONG SLEEVE TEE
    category: "tee",
    tagName: "stTshirt",
    price: 97.0,
    numbers: 0,
    inCart: false, //"./images/stTshirt.jpg",
    image: "https://static.footshop.com/254718/51953.jpg", //"./images/stTshirt.jpg",
  },
  /*vnTshirt:*/ {
    name: "VANS TRES CULEBRAS TEE",
    category: "tee",
    tagName: "vnTshirt",
    price: 34.0,
    numbers: 0,
    inCart: false, //"./images/vnTshirt.jpg",
    image: "https://static.footshop.com/253038/51074.jpg", //"./images/vnTshirt.jpg",
  },
  /*carhTr:*/ {
    name: "CARHARTT WIP PANTS", //CARHARTT WIP ELMWOOD PANTS
    category: "pants",
    tagName: "carhTr",
    price: 129.0,
    numbers: 0,
    inCart: false, //"./images/stTr.jpg",
    image: "https://static.footshop.com/256988/51558.jpg",
  },
  /*stTr:*/ {
    name: "STÜSSY DYED WORK PANTS",
    category: "pants",
    tagName: "stTr",
    price: 161.0,
    numbers: 0,
    inCart: false, //"./images/stTr.jpg",
    image: "https://static.footshop.com/256786/51981.jpg",
  },
  /*vnTr:*/ {
    name: "VANS EMBARCADERO PANTS",
    category: "pants",
    tagName: "vnTr",
    price: 78.0,
    numbers: 0,
    inCart: false, //"./images/vnTr.jpg",
    image: "https://static.footshop.com/253726/51093.jpg",
  },
];

//   id: 1,
//   category: "hoodie",
//   name: "CARHARTT WIP HOODIE", //CARHARTT WIP HOODED KLICKS SWEATSHIRT
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 113.0,
//   currency: "USD",
//   image: "https://static.footshop.com/236728/47495.jpg", //"./images/carhHood.jpg",
// },
// {
//   id: 2,
//   category: "hoodie",
//   name: "STÜSSY BASIC HOODIE",
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 114.0,
//   currency: "USD",
//   image: "https://static.footshop.com/256274/51950.jpg", //"./images/stHood.jpg",
// },
// {
//   id: 3,
//   category: "hoodie",
//   name: "VANS X GOLDBERG HOODIE", //VANS X JIM GOLDBERG SWEATSHIRT
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 100.0,
//   currency: "USD",
//   image: "https://static.footshop.com/254686/51173.jpg", //"./images/vnHood.jpg",
// },
// {
//   id: 4,
//   category: "tee",
//   name: "CARHARTT WIP POCKET TEE",
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 33.0,
//   currency: "USD",
//   image: "https://static.footshop.com/254090/51571.jpg", //"./images/carhTshirt.jpg",
// },
// {
//   id: 5,
//   category: "tee",
//   name: "STÜSSY LONG SLEEVE TEE", //STÜSSY BLEACH STRIPE CREW LONG SLEEVE TEE
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 97.0,
//   currency: "USD",
//   image: "https://static.footshop.com/254718/51953.jpg", //"./images/stTshirt.jpg",
// },
// {
//   id: 6,
//   category: "tee",
//   name: "VANS TRES CULEBRAS TEE",
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 34.0,
//   currency: "USD",
//   image: "https://static.footshop.com/253038/51074.jpg", //"./images/vnTshirt.jpg",
// },
// {
//   id: 7,
//   category: "pants",
//   name: "CARHARTT WIP PANTS", //CARHARTT WIP ELMWOOD PANTS
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 129.0,
//   currency: "USD",
//   image: "https://static.footshop.com/256988/51558.jpg", //"./images/stTr.jpg",
// },
// {
//   id: 8,
//   category: "pants",
//   name: "STÜSSY DYED WORK PANTS",
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 161.0,
//   currency: "USD",
//   image: "https://static.footshop.com/256786/51981.jpg", //"./images/stTr.jpg",
// },
// {
//   id: 9,
//   category: "pants",
//   name: "VANS EMBARCADERO PANTS",
//   size: [
//     { key: 1, text: "S", value: 1 },
//     { key: 2, text: "M", value: 2 },
//     { key: 3, text: "L", value: 3 },
//     { key: 4, text: "XL", value: 4 },
//   ],
//   price: 78.0,
//   currency: "USD",
//   image: "https://static.footshop.com/253726/51093.jpg", //"./images/vnTr.jpg",
// },
